### ISSUE TITLE
Optimize the item data writing to client

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/MasterSwordRebirth#26]
If we optimize the item data writing to via client, this should reduce overflows with large bags I think.

**Comment by BerntA** [comment]
Seems like usermessages dont like if you send more than 192 bytes for a player during one frame, while testing the API fetching on the game I crashed myself many times when printing debug stuff to the console, when I exceeded 192 bytes during a frame, apparently there is a client convar which could be set which determines the max usermessage size to recv each frame, I guess the max value is too low regardless though, and even worse if a client somehow sat this lower than 192 = rip..

**Comment by BerntA** [comment]
a lot of overflows are being triggered on linux:
ex:
SZ_GetSpace: overflow on MessageBegin/End
0xf76b2865 in Q_strlen (str=<optimized out>) at ../engine/common.c:219
SZ_GetSpace: 1342 is > full buffer size on MessageBegin/End, ignoringSZ_GetSpace: overflow on MessageBegin/End

due to usermessages being too large

**Comment by SaintWish** [comment]
Closing in favour of this issue https://github.com/MSRevive/MasterSwordRebirth/issues/140
