### ISSUE TITLE
Spells and Certain Ranged Equipment Should Use the Half Life 1 Reticle 

### ISSUE THREAD

**Issue by RWGryphon** [MSRevive/MasterSwordRebirth#75]
I believe this is in order to help players better judge where their healing spells like Rejuvenation will hit when casting it on players. Players will already need to learn to aim accordingly given knockback is no longer an avoidable topic without certain precautions and I think a reticle could help with the overall process. Additionally, it would actually make sense with the smaller crossbow as that model is not adjusted to work properly and aiming it has always been atrocious.

**Comment by SaintWish** [comment]
I was thinking instead of using the Half-Life crosshair sprites we can just make a simple dot in the middle of the screen. I think having a dot displayed at all times (even when you don't have an item out) would be good for players to know what they're even trying to pick up and stuff like that.

I was thinking of just creating a simple custom sprite of a white dot or whatever and use the [SetCrosshair](https://samvanheer.github.io/HLEnhanced/docs/cl__util_8h.html#aa69a591eee771ffda62c925668150fd3) engine function, but I haven't been able to get it to work just yet.
